dts: smith: resolve dtsi build issue
The node ois_rear is trying to deleted by
dvt* overlays, somehow this node is missing
and throws, node failure error.

 VERIFY  arch/arm64/boot/dts/vendor/qcom/lito-smith-dvt1a-overlay.dtbo
ERROR: ufdt_overlay_do_fixups():Couldn't find 'ois_rear' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay

Change-Id: If3373c5810135873c01129b36a56cf325ecbec60
Signed-off-by: Kanagarathina kalathi <kalathik@motorola.com>
Reviewed-on: https://gerrit.mot.com/1728411
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Vijayakumar Gn <vijaygn@motorola.com>
Reviewed-by: Ling Jin <lingjin@motorola.com>
Submit-Approved: Jira Key